### ISSUE TITLE
Version bumper script is incorrect

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/train-aws#19]
The version bumper script appears to work on Mac BSD sed but fails when using the containerized tools Expeditor uses.

See https://chefio.slack.com/archives/C4E7FS256/p1562020518012500

and https://chefio.slack.com/archives/C074S2A94/p1562020284052300

**Comment by zenspider** [comment]
that's on me. I made the BSD switch while patching up for a release and doing chef style.
